### PR TITLE
Fix navbar jumping when in blog page

### LINKED ISSUE #166: Blog - Top Navigation menu visually jumps compared to the other pages
https://www.operate-first.cloud/
vs
https://www.operate-first.cloud/blog

Peek 2022-08-02 13-25

### PR DESCRIPTION
**Pull request by Green-Ranger11**
This closes #166

### CODE REVIEW

**Comment by schwesig** [comment]
tested it in the preview
working great

thanks for this fast fix @Green-Ranger11

File: src/components/blog.tsx [hunk 1]
```diff
@@ -163,7 +163,7 @@ export const Blog = ({ posts }: PostsProps) => {
 
   return (
     <Layout>
-      <div className={classes.wrapper}>
+      <div className={classes.wrapper} style={{ minHeight: '90vh'}}>
```
Comment (schwesig) [inline src/components/blog.tsx:166]:
```suggestion
      <div className={classes.wrapper} style={{ minHeight: '90vh' }}>
```

**Comment by schwesig** [comment]
@Green-Ranger11 the pre-commit was failing because of
```diff
diff --git a/src/components/blog.tsx b/src/components/blog.tsx
index 7d2b9c4..cec0889 100644
--- a/src/components/blog.tsx
+++ b/src/components/blog.tsx
@@ -163,7 +163,7 @@ export const Blog = ({ posts }: PostsProps) => {
 
   return (
     <Layout>
-      <div className={classes.wrapper} style={{ minHeight: '90vh'}}>
+      <div className={classes.wrapper} style={{ minHeight: '90vh' }}>
         <SimpleGrid
           cols={3}
           mt="md"
```

so I added a commit to fix that
thanks for this good idea

**Review by schwesig — APPROVED** [review]
/lgtm
/approve
